### ISSUE TITLE
avoid using monkey-patch

### ISSUE THREAD

**Issue by msudgh** [delvedor/electron-is#11]
For some reason, [monkey-patch](https://en.wikipedia.org/wiki/Monkey_patch) dynamic modifications aren't preferred. I suggest to read [these ](https://www.beyondjava.net/what-about-monkey-patching-is-it-as-dangerous-as-they-say) pitfalls of monkey-patching and avoid using that in the library and also refactor the library.

**Comment by delvedor** [comment]
Pull request are [welcome](https://en.wikipedia.org/wiki/Welcome)!

**Comment by msudgh** [comment]
Great, As the library is less than 200 lines I'd like to use typescript, what do you think?

**Comment by delvedor** [comment]
You can definitely add the typings file, but I'd like the code to remain plain js.

**Comment by msudgh** [comment]
Sure.
