### ISSUE TITLE
Why functions in the first place?

### ISSUE THREAD

**Issue by DimitarNestorov** [delvedor/electron-is#13]
What I don't get is why `is.osx()` instead of `is.osx`. `process.platform` will only change if the developer explicitly changes it, same goes for the others.

**Comment by delvedor** [comment]
Hi! The answer is API consistency. Everything is exposed as a function, so you don't need to read the docs or wait to an exception to be thrown to figure out if it was a function or a boolean.
In this way is also possible to continue to add APIs easily in the future, and handle breaking changes of the underline API.

Thank you for your proposal, but I don't want to change the current API.
