### ISSUE TITLE
Cannot be uglified in Webpack. 

### ISSUE THREAD

**Issue by michaeljota** [delvedor/electron-is#7]
As I said in #5, right now this can't be uglified with Webpack. I don't know what would be a better approach. 

I would like to load this directly, I don't know if you are willing to make this a ES5 module, or if that it's even possible, cause you use `...` and I don't know how to imite it with ES5.

**Comment by delvedor** [comment]
Since version 1.x.x Electron uses Node v6, that is almost fully compliant with ES6.
As said in the pr this is a module built specifically for electron.
If you have this kind of problem because of the browser, you can add a transpile step to your webpack flow.

**Comment by michaeljota** [comment]
Actually I don't have any problems in the browser, but when I try to webpack it to electron it self. 

Thanks anyway.

**Comment by delvedor** [comment]
Maybe I'm saying a stupid thing, but why use webpack inside electron?
Electron gives you the `require` natively inside the browser, without need to use webpack/browserify.

**Comment by michaeljota** [comment]
It's not to required. It's just to get a single file and load the app from there.

**Comment by delvedor** [comment]
Here we are entering in the magic field of the preferences, but in my opinion here webpack is only an useless step. You are using Webpack because of the require, but electron supports require, so why use it?
You can easily add an entry point to the html (just one file) and then require all the files, the same as you do in the main process.

**Comment by michaeljota** [comment]
I'm actually packing the main file. I'm developing in Typescript, so webpack here does a little more than just the require step. 

But, as you said, it's preferences.

**Comment by komplexb** [comment]
```
ERROR in build.js from UglifyJs
SyntaxError: Name expected [./app/~/electron-is/is.js:12,0]
```
Should I assume this error i'm experiencing is the same as this issue thread?
Does using `const is = require('electron-is')` resolve it? Because I tried that instead of `import...` but I still get the error.

**Comment by delvedor** [comment]
Probably is something related to this.
https://github.com/terinjokes/gulp-uglify/issues/66
https://github.com/webpack/webpack/issues/2972

I'll update the lib converting the es6 code, and we'll see if that solves the problem.

**Comment by komplexb** [comment]
Hey @delvedor this is unrelated. Have you seen anything like this when trying to running an Electron production build?
```
Uncaught Exception:
Error: EACCES: permission denied, mkdir '/.node-persist'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
```

**Comment by delvedor** [comment]
@komplexb which OS are you using?

**Comment by komplexb** [comment]
@delvedor OSX. 
Let me know if there's a better forum we can discuss, instead of polluting this thread too much.

**Comment by delvedor** [comment]
On macOS you can't create files/folders inside your executable, you must do it outside, like in `~/Home`.

A good place to ask this kind of question is here :)
https://discuss.atom.io/c/electron

**Comment by komplexb** [comment]
Ok, lemme try that. Thanks.

**Comment by delvedor** [comment]
@michaeljota  and @komplexb I've created a branch (#8) with the fixes, could you test it?

**Comment by komplexb** [comment]
Do I just need to download https://github.com/delvedor/electron-is/blob/remove-es6/is.js and `import` or `require`?

**Comment by delvedor** [comment]
Yep! :)

**Comment by komplexb** [comment]
Keeps harping on semver...
```
Uncaught Exception:
Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/
```
<img width="429" alt="screenshot 2016-12-14 17 00 13" src="https://cloud.githubusercontent.com/assets/3874813/21203103/f6233d6c-c21e-11e6-8ad0-5d71029c3d84.png">

**Comment by delvedor** [comment]
Mh, did you try to wipe out the `node_modules` folder and the reinstall everything again?

```bash
rm -rf node_modules
npm i
```

**Comment by delvedor** [comment]
@komplexb news?

**Comment by komplexb** [comment]
I'll try your suggestion over the weekend.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Dec 16, 2016 at 3:43 AM -0500, "Tomas Della Vedova" <notifications@github.com<mailto:notifications@github.com>> wrote:


@komplexb<https://github.com/komplexb> news?

**Comment by komplexb** [comment]
@delvedor works now 👍🏾👌🏾

**Comment by delvedor** [comment]
Perfect, thank you for the collaboration!

**Comment by komplexb** [comment]
Hey @delvedor new-ish error. Just a heads-up, UglifyJS hates back-ticks. [Patching your file](https://github.com/delvedor/electron-is/files/938984/is.custom.js.txt) was easier to do than getting UglifyJS harmony to work.

```
ERROR in build.js from UglifyJs
SyntaxError: Unexpected character '`' [build.js:20342,14]

ERROR in build.js from UglifyJs
SyntaxError: Unexpected character '`' [./app/~/electron-is/is.js:126,0]
```

**Comment by delvedor** [comment]
Hi @komplexb, yes, uglify does not support es6. 
If you add a module like [es2020](https://github.com/yoshuawuyts/es2020) to your build pipeline it should solve the issue.
